// DropdownValues.js

const ivRemarks = [
  { id: 1, remark: "Already done in same month" },
  { id: 2, remark: "Appt Cancelled" },
  { id: 3, remark: "Discounted Plan" },
  { id: 4, remark: "Benefit maxed out as per ES" },
  { id: 5, remark: "Benefit Response not Received" },
  { id: 6, remark: "Benefits not available on web" },
  { id: 7, remark: "Call insurance for policy holder" },
  { id: 8, remark: "Cash Patient - office" },
  { id: 9, remark: "Cash Patient - PI Team" },
  { id: 10, remark: "Completed" },
  { id: 11, remark: "Completed as Per Recall/Contx Workfow" },
  { id: 12, remark: "Coverage book Not available (HMO) (Day Team)" },
  { id: 13, remark: "Database Not Available (Day Team)" },
  { id: 14, remark: "Dependent not enrolled" },
  { id: 15, remark: "Emailed To Beam" },
  { id: 16, remark: "Fax not received" },
  { id: 17, remark: "Faxback Attached in SD" },
  { id: 18, remark: "Future activation date" },
  { id: 19, remark: "Inactive" },
  { id: 20, remark: "INCOMPLETE - Night IV needs to call for Benefits" },
  { id: 21, remark: "INCOMPLETE - Office needs to call for Benefits" },
  {
    id: 22,
    remark: "INCOMPLETE - Office needs to call for Benefits & History",
  },
  { id: 23, remark: "INCOMPLETE - Office needs to call for History" },
  { id: 24, remark: "Incomplete Information" },
  { id: 25, remark: "Ineligible" },
  { id: 26, remark: "Maintenance in Portal (Day Team)" },
  { id: 27, remark: "Maxed Out" },
  { id: 28, remark: "Medicaid IVs (Day Team)" },
  { id: 29, remark: "Medicaid IVs for Future Dates (Day Team)" },
  { id: 30, remark: "Medical Policy" },
  { id: 31, remark: "Missing Insurance Details" },
  { id: 32, remark: "No Dental Coverage" },
  { id: 33, remark: "No OON Benefits" },
  { id: 34, remark: "No OS Benefits" },
  { id: 35, remark: "Not able to contact with rep" },
  { id: 36, remark: "Not assigned to our office" },
  { id: 37, remark: "Not Found over Call" },
  { id: 38, remark: "office Closed" },
  { id: 39, remark: "Office denied to do the IV" },
  { id: 40, remark: "Only Ortho IV required as per ofc" },
  { id: 41, remark: "Only OS IV required as per ofc" },
  { id: 42, remark: "OS Patient" },
  { id: 43, remark: "Indemnity plan" },
  { id: 44, remark: "PCS Not Available (HMO) (Day Team)" },
  { id: 45, remark: "Pediatric Plan" },
  { id: 46, remark: "Policy Cancelled" },
  { id: 47, remark: "Portal Not Available (Day Team)" },
  { id: 48, remark: "Portal Not Working (Day Team)" },
  { id: 49, remark: "Previous Month" },
  { id: 50, remark: "Rep denied to provide info" },
  { id: 51, remark: "Repeated" },
  { id: 52, remark: "Return to Office" },
  { id: 53, remark: "Rush not Accepted" },
  { id: 54, remark: "Technical Issues" },
  { id: 55, remark: "Terminated" },
  { id: 56, remark: "Third party Issue - Office need to call" },
  { id: 57, remark: "To be done by Office" },
  { id: 58, remark: "To be Started" },
  { id: 59, remark: "Unable to retrive information" },
  { id: 60, remark: "Wrong information" },
  { id: 61, remark: "Provider not available on Provider Schedule" },
  { id: 62, remark: "Not Found over web, Night IV need to call" },
  { id: 63, remark: "Not found on web and call" },
  { id: 64, remark: "Not accepting HMO patient" },
  { id: 65, remark: "Completed, Not updated in ES, IV emailed" },
  { id: 66, remark: "Missing Insurance Details, No info ES" },
  { id: 67, remark: "Not Found over web" },
  { id: 68, remark: "Ortho/OS Provider on Scheduler" },
  { id: 69, remark: "IV Return - TX on Exchange above 18 years" },
  {
    id: 70,
    remark: "Office Is closed for the day, Patient need to reschedule.",
  },
  { id: 71, remark: "Faxback Attached in Drive" },
  { id: 72, remark: "Completed, Not assigned to Facility" },
  { id: 73, remark: "Technical Issue - Not received OTP/Fax" },
  { id: 74, remark: "Unable to check Provider/Facility Status" },
  { id: 75, remark: "Updated ES, IV has not created" },
  { id: 76, remark: "IV not created, Email sent for benefits" },
];

const sourceDropdownOptions = [
  { id: 1, source: "DB" },
  { id: 2, source: "DB + Call" },
  { id: 3, source: "DB + Web" },
  { id: 4, source: "DB + Fax" },
  { id: 5, source: "DB + Fax + Web" },
  { id: 6, source: "DB + Fax + Call" },
  { id: 7, source: "DB + Web + Call" },
  { id: 8, source: "Fax + DB + Web + Call" },
  { id: 9, source: "Call" },
  { id: 10, source: "Website" },
  { id: 11, source: "Fax" },
  { id: 12, source: "MDB" },
  { id: 13, source: "MDB + Call" },
  { id: 14, source: "MDB + Web" },
  { id: 15, source: "MDB + Fax" },
  { id: 16, source: "MDB + Fax + Call" },
  { id: 17, source: "MDB + Web + Call" },
  { id: 18, source: "Fax + MDB + Web + Call" },
  { id: 19, source: "Call + Web" },
  { id: 20, source: "Scraping Tool" },
  { id: 21, source: "MDB + Web + Call" },
  { id: 22, source: "Fax + Web" },
  { id: 23, source: "Fax + Call" },
  { id: 24, source: "Scraping + Web + Call" },
  { id: 25, source: "Scraping Tool + Web" },
  { id: 26, source: "RTE + DB" },
  { id: 27, source: "RTE + Call" },
  { id: 28, source: "RTE + Web" },
  { id: 29, source: "RTE + MDB + Call" },
  { id: 30, source: "RTE + MDB" },
  { id: 31, source: "BaseTemplate" },
  { id: 32, source: "BaseTemplate + Web" },
  { id: 33, source: "BaseTemplate + Call" },
  { id: 34, source: "DB + Chat" },
  { id: 35, source: "DB + Web + Chat" },
  { id: 36, source: "Web + Chat" },
  { id: 37, source: "MDB + Web + Chat" },
  { id: 38, source: "MDB + Chat" },
  { id: 39, source: "Call + Chat" },
];

const planTypeDropdownOptions = [
  { id: 1, planType: "Child Medicaid" },
  { id: 2, planType: "Medicare" },
  { id: 3, planType: "PPO" },
  { id: 4, planType: "HMO" },
  { id: 5, planType: "EPO" },
  { id: 6, planType: "DDPO" },
  { id: 7, planType: "Indemnity" },
  { id: 8, planType: "Adult Medicaid" },
  { id: 9, planType: "Discounted Plan" },
  { id: 10, planType: "INO" },
  { id: 11, planType: "Medical Policy" },
  { id: 12, planType: "Standard" },
  { id: 13, planType: "Self Funded" },
  { id: 14, planType: "Texas Medicare Medicaid" },
  { id: 15, planType: "Pediatric Plan" },
  { id: 16, planType: "PPO (OUT)" },
  { id: 17, planType: "HMO Medicare" },
];

const officeNames = [
  { id: 1, officeName: "Aransas" },
  { id: 2, officeName: "Azle" },
  { id: 3, officeName: "Beaumont" },
  { id: 4, officeName: "Benbrook" },
  { id: 5, officeName: "Brodie" },
  { id: 6, officeName: "Calallen" },
  { id: 7, officeName: "Crosby" },
  { id: 8, officeName: "Devine" },
  { id: 9, officeName: "Elgin" },
  { id: 10, officeName: "Huffman" },
  { id: 11, officeName: "Jasper" },
  { id: 12, officeName: "Lavaca" },
  { id: 13, officeName: "Liberty" },
  { id: 14, officeName: "Lucas" },
  { id: 15, officeName: "Lytle" },
  { id: 16, officeName: "Mathis" },
  { id: 17, officeName: "Potranco" },
  { id: 18, officeName: "Rio Bravo" },
  { id: 19, officeName: "Riverwalk" },
  { id: 20, officeName: "Rockdale" },
  { id: 21, officeName: "Rockwall" },
  { id: 22, officeName: "San Mateo" },
  { id: 23, officeName: "Sinton" },
  { id: 24, officeName: "Splendora" },
  { id: 25, officeName: "Springtown" },
  { id: 26, officeName: "Tidwell" },
  { id: 27, officeName: "Victoria" },
  { id: 28, officeName: "Westgreen" },
  { id: 29, officeName: "Winnie" },
];

export {
  ivRemarks,
  sourceDropdownOptions,
  planTypeDropdownOptions,
  officeNames,
};
