// DropdownValues.js

const ivRemarksDropdownOptions = [
  { id: 1, ivRemarks: "Already done in same month" },
  { id: 2, ivRemarks: "Appt Cancelled" },
  { id: 3, ivRemarks: "Discounted Plan" },
  { id: 4, ivRemarks: "Benefit maxed out as per ES" },
  { id: 5, ivRemarks: "Benefit Response not Received" },
  { id: 6, ivRemarks: "Benefits not available on web" },
  { id: 7, ivRemarks: "Call insurance for policy holder" },
  { id: 8, ivRemarks: "Cash Patient - office" },
  { id: 9, ivRemarks: "Cash Patient - PI Team" },
  { id: 10, ivRemarks: "Completed" },
  { id: 11, ivRemarks: "Completed as Per Recall/Contx Workfow" },
  { id: 12, ivRemarks: "Coverage book Not available (HMO) (Day Team)" },
  { id: 13, ivRemarks: "Database Not Available (Day Team)" },
  { id: 14, ivRemarks: "Dependent not enrolled" },
  { id: 15, ivRemarks: "Emailed To Beam" },
  { id: 16, ivRemarks: "Fax not received" },
  { id: 17, ivRemarks: "Faxback Attached in SD" },
  { id: 18, ivRemarks: "Future activation date" },
  { id: 19, ivRemarks: "Inactive" },
  { id: 20, ivRemarks: "INCOMPLETE - Night IV needs to call for Benefits" },
  { id: 21, ivRemarks: "INCOMPLETE - Office needs to call for Benefits" },
  {
    id: 22,
    ivRemarks: "INCOMPLETE - Office needs to call for Benefits & History",
  },
  { id: 23, ivRemarks: "INCOMPLETE - Office needs to call for History" },
  { id: 24, ivRemarks: "Incomplete Information" },
  { id: 25, ivRemarks: "Ineligible" },
  { id: 26, ivRemarks: "Maintenance in Portal (Day Team)" },
  { id: 27, ivRemarks: "Maxed Out" },
  { id: 28, ivRemarks: "Medicaid IVs (Day Team)" },
  { id: 29, ivRemarks: "Medicaid IVs for Future Dates (Day Team)" },
  { id: 30, ivRemarks: "Medical Policy" },
  { id: 31, ivRemarks: "Missing Insurance Details" },
  { id: 32, ivRemarks: "No Dental Coverage" },
  { id: 33, ivRemarks: "No OON Benefits" },
  { id: 34, ivRemarks: "No OS Benefits" },
  { id: 35, ivRemarks: "Not able to contact with rep" },
  { id: 36, ivRemarks: "Not assigned to our office" },
  { id: 37, ivRemarks: "Not Found over Call" },
  { id: 38, ivRemarks: "office Closed" },
  { id: 39, ivRemarks: "Office denied to do the IV" },
  { id: 40, ivRemarks: "Only Ortho IV required as per ofc" },
  { id: 41, ivRemarks: "Only OS IV required as per ofc" },
  { id: 42, ivRemarks: "OS Patient" },
  { id: 43, ivRemarks: "Indemnity plan" },
  { id: 44, ivRemarks: "PCS Not Available (HMO) (Day Team)" },
  { id: 45, ivRemarks: "Pediatric Plan" },
  { id: 46, ivRemarks: "Policy Cancelled" },
  { id: 47, ivRemarks: "Portal Not Available (Day Team)" },
  { id: 48, ivRemarks: "Portal Not Working (Day Team)" },
  { id: 49, ivRemarks: "Previous Month" },
  { id: 50, ivRemarks: "Rep denied to provide info" },
  { id: 51, ivRemarks: "Repeated" },
  { id: 52, ivRemarks: "Return to Office" },
  { id: 53, ivRemarks: "Rush not Accepted" },
  { id: 54, ivRemarks: "Technical Issues" },
  { id: 55, ivRemarks: "Terminated" },
  { id: 56, ivRemarks: "Third party Issue - Office need to call" },
  { id: 57, ivRemarks: "To be done by Office" },
  { id: 58, ivRemarks: "To be Started" },
  { id: 59, ivRemarks: "Unable to retrive information" },
  { id: 60, ivRemarks: "Wrong information" },
  { id: 61, ivRemarks: "Provider not available on Provider Schedule" },
  { id: 62, ivRemarks: "Not Found over web, Night IV need to call" },
  { id: 63, ivRemarks: "Not found on web and call" },
  { id: 64, ivRemarks: "Not accepting HMO patient" },
  { id: 65, ivRemarks: "Completed, Not updated in ES, IV emailed" },
  { id: 66, ivRemarks: "Missing Insurance Details, No info ES" },
  { id: 67, ivRemarks: "Not Found over web" },
  { id: 68, ivRemarks: "Ortho/OS Provider on Scheduler" },
  { id: 69, ivRemarks: "IV Return - TX on Exchange above 18 years" },
  {
    id: 70,
    ivRemarks: "Office Is closed for the day, Patient need to reschedule.",
  },
  { id: 71, ivRemarks: "Faxback Attached in Drive" },
  { id: 72, ivRemarks: "Completed, Not assigned to Facility" },
  { id: 73, ivRemarks: "Technical Issue - Not received OTP/Fax" },
  { id: 74, ivRemarks: "Unable to check Provider/Facility Status" },
  { id: 75, ivRemarks: "Updated ES, IV has not created" },
  { id: 76, ivRemarks: "IV not created, Email sent for benefits" },
];

const sourceDropdownOptions = [
  { id: 1, source: "DB" },
  { id: 2, source: "DB + Call" },
  { id: 3, source: "DB + Web" },
  { id: 4, source: "DB + Fax" },
  { id: 5, source: "DB + Fax + Web" },
  { id: 6, source: "DB + Fax + Call" },
  { id: 7, source: "DB + Web + Call" },
  { id: 8, source: "Fax + DB + Web + Call" },
  { id: 9, source: "Call" },
  { id: 10, source: "Website" },
  { id: 11, source: "Fax" },
  { id: 12, source: "MDB" },
  { id: 13, source: "MDB + Call" },
  { id: 14, source: "MDB + Web" },
  { id: 15, source: "MDB + Fax" },
  { id: 16, source: "MDB + Fax + Call" },
  { id: 17, source: "MDB + Web + Call" },
  { id: 18, source: "Fax + MDB + Web + Call" },
  { id: 19, source: "Call + Web" },
  { id: 20, source: "Scraping Tool" },
  { id: 21, source: "MDB + Web + Call" },
  { id: 22, source: "Fax + Web" },
  { id: 23, source: "Fax + Call" },
  { id: 24, source: "Scraping + Web + Call" },
  { id: 25, source: "Scraping Tool + Web" },
  { id: 26, source: "RTE + DB" },
  { id: 27, source: "RTE + Call" },
  { id: 28, source: "RTE + Web" },
  { id: 29, source: "RTE + MDB + Call" },
  { id: 30, source: "RTE + MDB" },
  { id: 31, source: "BaseTemplate" },
  { id: 32, source: "BaseTemplate + Web" },
  { id: 33, source: "BaseTemplate + Call" },
  { id: 34, source: "DB + Chat" },
  { id: 35, source: "DB + Web + Chat" },
  { id: 36, source: "Web + Chat" },
  { id: 37, source: "MDB + Web + Chat" },
  { id: 38, source: "MDB + Chat" },
  { id: 39, source: "Call + Chat" },
];

const planTypeDropdownOptions = [
  { id: 1, planType: "Child Medicaid" },
  { id: 2, planType: "Medicare" },
  { id: 3, planType: "PPO" },
  { id: 4, planType: "HMO" },
  { id: 5, planType: "EPO" },
  { id: 6, planType: "DDPO" },
  { id: 7, planType: "Indemnity" },
  { id: 8, planType: "Adult Medicaid" },
  { id: 9, planType: "Discounted Plan" },
  { id: 10, planType: "INO" },
  { id: 11, planType: "Medical Policy" },
  { id: 12, planType: "Standard" },
  { id: 13, planType: "Self Funded" },
  { id: 14, planType: "Texas Medicare Medicaid" },
  { id: 15, planType: "Pediatric Plan" },
  { id: 16, planType: "PPO (OUT)" },
  { id: 17, planType: "HMO Medicare" },
];

const officeNames = [
  { id: 1, officeName: "Aransas" },
  { id: 2, officeName: "Azle" },
  { id: 3, officeName: "Beaumont" },
  { id: 4, officeName: "Benbrook" },
  { id: 5, officeName: "Calallen" },
  { id: 6, officeName: "Crosby" },
  { id: 7, officeName: "Devine" },
  { id: 8, officeName: "Elgin" },
  { id: 9, officeName: "Grangerland" },
  { id: 10, officeName: "Huffman" },
  { id: 11, officeName: "Jasper" },
  { id: 12, officeName: "Lavaca" },
  { id: 13, officeName: "Liberty" },
  { id: 14, officeName: "Lytle" },
  { id: 15, officeName: "Mathis" },
  { id: 16, officeName: "Potranco" },
  { id: 17, officeName: "Rio Bravo" },
  { id: 18, officeName: "Riverwalk" },
  { id: 19, officeName: "Rockdale" },
  { id: 20, officeName: "Sinton" },
  { id: 21, officeName: "Splendora" },
  { id: 22, officeName: "Springtown" },
  { id: 23, officeName: "Tidwell" },
  { id: 24, officeName: "Victoria" },
  { id: 25, officeName: "Westgreen" },
  { id: 26, officeName: "Winnie" },
 
];

const insuranceNames = [
    { "id": 1, "name": "32 DENTAL" },
    { "id": 2, "name": "6 Degrees Health" },
    { "id": 3, "name": "90 Degree Benefits" },
    { "id": 4, "name": "Administrative Concepts, Inc" },
    { "id": 5, "name": "Adroit Health group" },
    { "id": 6, "name": "Aetna Dental DMO/HMO" },
    { "id": 7, "name": "Aetna Dental PPO" },
    { "id": 8, "name": "Aetna Medicare" },
    { "id": 9, "name": "Aflac Dental" },
    { "id": 10, "name": "All Savers" },
    { "id": 11, "name": "Allegiance Benefit Plan Management" },
    { "id": 12, "name": "Allied" },
    { "id": 13, "name": "Allstate Health Solutions" },
    { "id": 14, "name": "Allwell & Better" },
    { "id": 15, "name": "Alternative Benefit Plans" },
    { "id": 16, "name": "Always Care" },
    { "id": 17, "name": "Ambetter" },
    { "id": 18, "name": "America's Choice Healthplans" },
    { "id": 19, "name": "American Dental Network" },
    { "id": 20, "name": "American General Life Co. AIG" },
    { "id": 21, "name": "American Public Life Insurance Co" },
    { "id": 22, "name": "AmeriGroup" },
    { "id": 23, "name": "Ameritas" },
    { "id": 24, "name": "Anthem BCBS" },
    { "id": 25, "name": "Anthem of IN" },
    { "id": 26, "name": "APWU Health Plan" },
    { "id": 27, "name": "Argus Dental & Vision" },
    { "id": 28, "name": "Asserta Health" },
    { "id": 29, "name": "Assurant Employee Benefits" },
    { "id": 30, "name": "Assurant Supplemental Coverage" },
    { "id": 31, "name": "Automated Benefit Services" },
    { "id": 32, "name": "BAC" },
    { "id": 33, "name": "BASE_AETNA" },
    { "id": 34, "name": "BASE_AMERITAS" },
    { "id": 35, "name": "BASE_BCBS" },
    { "id": 36, "name": "BASE_BCBS TX" },
    { "id": 37, "name": "BASE_CIGNA" },
    { "id": 38, "name": "BASE_DELTA DENTAL" },
    { "id": 39, "name": "BASE_GUARDIAN" },
    { "id": 40, "name": "BASE_HUMANA" },
    { "id": 41, "name": "BASE_METLIFE" },
    { "id": 42, "name": "BASE_PRINCIPAL" },
    { "id": 43, "name": "BASE_UCCI" },
    { "id": 44, "name": "BASE_UHC PPO" },
    { "id": 45, "name": "BaylorScott & White Health Plan" },
    { "id": 46, "name": "BCBS - NEIHBP" },
    { "id": 47, "name": "BCBS - Plumbers Local Union 68" },
    { "id": 48, "name": "BCBS Of AL" },
    { "id": 49, "name": "BCBS of AR" },
    { "id": 50, "name": "BCBS Of Florida" },
    { "id": 51, "name": "BCBS Of GA" },
    { "id": 52, "name": "BCBS of Idaho" },
    { "id": 53, "name": "BCBS Of IL" },
    { "id": 54, "name": "Blue Cross & Blue Shield of Kansas City" },
    { "id": 55, "name": "BCBS Of LA" },
    { "id": 56, "name": "BCBS Of MA" },
    { "id": 57, "name": "BCBS Of MI" },
    { "id": 58, "name": "BCBS of Minnesota" },
    { "id": 59, "name": "BCBS of Nebraska" },
    { "id": 60, "name": "BCBS Of NJ" },
    { "id": 61, "name": "BCBS of NM" },
    { "id": 62, "name": "BCBS Of North Carolina" },
    { "id": 63, "name": "BCBS of North Dakota" },
    { "id": 64, "name": "BCBS Of OK" },
    { "id": 65, "name": "BCBS of Oregon" },
    { "id": 66, "name": "BCBS Of PA" },
    { "id": 67, "name": "BCBS Of SC" },
    { "id": 68, "name": "BCBS Of Texas - Federal Government" },
    { "id": 69, "name": "BCBS Of TN" },
    { "id": 70, "name": "BCBS Of TX" },
    { "id": 71, "name": "BCBS Of UT" },
    { "id": 72, "name": "BCBS Of WA" },
    { "id": 73, "name": "BCS" },
    { "id": 74, "name": "Beam" },
    { "id": 75, "name": "Benefits Services of America" },
    { "id": 76, "name": "BenefitSource Inc." },
    { "id": 77, "name": "Bento" },
    { "id": 78, "name": "Best Life & Health Insurance Co." },
    { "id": 79, "name": "Blue Shield of California" },
    { "id": 80, "name": "BlueAdvantage Administrators of Arkansas" },
    { "id": 81, "name": "Boon Chapman" },
    { "id": 82, "name": "Bright Benefits" },
    { "id": 83, "name": "Bright Idea Dental" },
    { "id": 84, "name": "Canopy Health" },
    { "id": 85, "name": "Capital BC(Dominion National)" },
    { "id": 86, "name": "Caprock" },
    { "id": 87, "name": "Care First Administrators" },
    { "id": 88, "name": "Careington Benefits Solutions" },
    { "id": 89, "name": "Centivo" },
    { "id": 90, "name": "Chesapeake Life Co" },
    { "id": 91, "name": "Chesterfield Resources" },
    { "id": 92, "name": "Christian Brothers" },
    { "id": 93, "name": "CHRISTUS Health Plan" },
    { "id": 94, "name": "Cigna Dental" },
    { "id": 95, "name": "Cigna Dental - AT&T ONLY" },
    { "id": 96, "name": "Cigna Dental DHMO" },
    { "id": 97, "name": "Cigna Global Health Benefits" },
    { "id": 98, "name": "Colonial Life Dental" },
    { "id": 99, "name": "Community Health Choice" },
    { "id": 100, "name": "Companion Life" },
    { "id": 101, "name": "Concierge Dental Design" },
    { "id": 102, "name": "Connection Dental - GEHA" },
    { "id": 103, "name": "Convergent Health One" },
    { "id": 104, "name": "Core Source" },
    { "id": 105, "name": "Credence Blue Cross and Blue Shield" },
    { "id": 106, "name": "Curative" },
    { "id": 107, "name": "Dearborn National" },
    { "id": 108, "name": "Delta Care USA - HMO" },
    { "id": 109, "name": "Delta Dental Northeast" },
    { "id": 110, "name": "Delta Dental Of Alabama" },
    { "id": 111, "name": "Delta Dental of Arizona" },
    { "id": 112, "name": "Delta Dental Of Arkansas" },
    { "id": 113, "name": "Delta Dental Of CA Fed. Gov. Prog." },
    { "id": 114, "name": "Delta Dental Of California" },
    { "id": 115, "name": "Delta Dental Of Colarado" },
    { "id": 116, "name": "Delta Dental Of Delaware" },
    { "id": 117, "name": "Delta Dental Of Florida" },
    { "id": 118, "name": "Delta Dental Of Georgia" },
    { "id": 119, "name": "Delta Dental Of Idaho" },
    { "id": 120, "name": "Delta Dental Of Illinois" },
    { "id": 121, "name": "Delta Dental Of Indiana" },
    { "id": 122, "name": "Delta Dental Of Iowa" },
    { "id": 123, "name": "Delta Dental Of Kansas" },
    { "id": 124, "name": "Delta Dental Of Kentucky" },
    { "id": 125, "name": "Delta Dental Of Louisiana" },
    { "id": 126, "name": "Delta Dental Of Maryland" },
    { "id": 127, "name": "Delta Dental of Massachusetts" },
    { "id": 128, "name": "Delta Dental Of Michigan" },
    { "id": 129, "name": "Delta Dental Of Minnesota" },
    { "id": 130, "name": "Delta Dental Of Mississippi" },
    { "id": 131, "name": "Delta Dental of Missouri" },
    { "id": 132, "name": "Delta Dental Of Montana" },
    { "id": 133, "name": "Delta Dental Of Nebraska" },
    { "id": 134, "name": "Delta Dental Of Nevada" },
    { "id": 135, "name": "Delta Dental Of New Hampshire" },
    { "id": 136, "name": "Delta Dental of New Jersey" },
    { "id": 137, "name": "Delta Dental Of New Jersey & Connecticut" },
    { "id": 138, "name": "Delta Dental Of New Mexico" },
    { "id": 139, "name": "Delta Dental Of New York" },
    { "id": 140, "name": "Delta Dental Of North Carolina" },
    { "id": 141, "name": "Delta Dental Of North Dakota" },
    { "id": 142, "name": "Delta Dental Of Ohio" },
    { "id": 143, "name": "Delta Dental Of Oklahoma" },
    { "id": 144, "name": "Delta Dental of Oregon" },
    { "id": 145, "name": "Delta Dental Of Pennsylvania" },
    { "id": 146, "name": "Delta Dental of Rhode Island" },
    { "id": 147, "name": "Delta Dental Of South Dakota" },
    { "id": 148, "name": "Delta Dental Of Tennessee" },
    { "id": 149, "name": "Delta Dental Of Texas" },
    { "id": 150, "name": "Delta Dental Of Utah" },
    { "id": 151, "name": "Delta Dental of Virginia" },
    { "id": 152, "name": "Delta Dental of Washington" },
    { "id": 153, "name": "Delta Dental Of West Virginia" },
    { "id": 154, "name": "Delta Dental of Wisconsin" },
    { "id": 155, "name": "Delta Dental Of Wyoming" },
    { "id": 156, "name": "Deltacare USA" },
    { "id": 157, "name": "Denta Trust" },
    { "id": 158, "name": "Dental Meridian Plan" },
    { "id": 159, "name": "Dental Select" },
    { "id": 160, "name": "DentaQuest - Adult Medicaid" },
    { "id": 161, "name": "DentaQuest - Care n Care" },
    { "id": 162, "name": "DentaQuest - Child Medicaid" },
    { "id": 163, "name": "DentaQuest - Chip" },
    { "id": 164, "name": "DentaQuest - Cigna HMO" },
    { "id": 165, "name": "DentaQuest - Fostercare" },
    { "id": 166, "name": "DentaQuest - Medicare" },
    { "id": 167, "name": "DentaQuest - PPO" },
    { "id": 168, "name": "DentaQuest - Star Pregnant Women" },
    { "id": 169, "name": "DentaQuest - Superior Health Plan" },
    { "id": 170, "name": "DentaQuest - WellCare HMO" },
    { "id": 171, "name": "Dentaquest of New Mexico" },
    { "id": 172, "name": "Dentegra Insurance Company" },
    { "id": 173, "name": "Dentemax" },
    { "id": 174, "name": "Devoted Health, Inc." },
    { "id": 175, "name": "Dina Dental" },
    { "id": 176, "name": "Direct Care" },
    { "id": 177, "name": "Driscol" },
    { "id": 178, "name": "Emblem Health" },
    { "id": 179, "name": "EMI Health" },
    { "id": 180, "name": "Encore Dental PPO" },
    { "id": 181, "name": "Entrust" },
    { "id": 182, "name": "Envolve Dental" },
    { "id": 183, "name": "Equitable Health" },
    { "id": 184, "name": "Essential Staffcare (PAI)" },
    { "id": 185, "name": "EVHC" },
    { "id": 186, "name": "FEP Blue Dental" },
    { "id": 187, "name": "FCL Dental" },
    { "id": 188, "name": "Foundation Dental" },
    { "id": 189, "name": "Freedom Life Group" },
    { "id": 190, "name": "GEHA" },
    { "id": 191, "name": "Gilspar llc" },
    { "id": 192, "name": "GNA Partners" },
    { "id": 193, "name": "Gravie Administrative Services" },
    { "id": 194, "name": "Group & Pension Administrators, Inc." },
    { "id": 195, "name": "Guardian - PPO" },
    { "id": 196, "name": "Guardian - HMO" },
    { "id": 197, "name": "Hawaii Dental Service" },
    { "id": 198, "name": "Health First Benefits" },
    { "id": 199, "name": "Health Plans INC" },
    { "id": 200, "name": "Healthcare Highways" },
    { "id": 201, "name": "HealthComp Integrated Solutions" },
    { "id": 202, "name": "Healthgram" },
    { "id": 203, "name": "HealthPartners" },
    { "id": 204, "name": "Healthscope" },
    { "id": 205, "name": "HealthSmart Benefit Solutions Inc." },
    { "id": 206, "name": "Highmark Wholecare" },
    { "id": 207, "name": "Hiscox Insurance" },
    { "id": 208, "name": "Hooray Health" },
    { "id": 209, "name": "Horizon Blue Cross Blue Shiled of NJ" },
    { "id": 210, "name": "Humana Federal" },
    { "id": 211, "name": "Humana Federal EPO" },
    { "id": 212, "name": "Humana HMO" },
    { "id": 213, "name": "Humana Medicare" },
    { "id": 214, "name": "Humana PPO" },
    { "id": 215, "name": "Humana- Speciality Benefits" },
    { "id": 216, "name": "IHC Health Solutions" },
    { "id": 217, "name": "Imagine 360" },
    { "id": 218, "name": "IMG" },
    { "id": 219, "name": "Insurance Management Services" },
    { "id": 220, "name": "Iron Workers Local 263 Benefits" },
    { "id": 221, "name": "Kansas City Life Insurance" },
    { "id": 222, "name": "Kelsey Care Advantage" },
    { "id": 223, "name": "Level Dental" },
    { "id": 224, "name": "Liberty Dental Plan" },
    { "id": 225, "name": "Liberty Dental Plan - DADS Waiver" },
    { "id": 226, "name": "Liberty Dental Plan - Star Plus" },
    { "id": 227, "name": "Liberty Medicare Advantage" },
    { "id": 228, "name": "Life Map" },
    { "id": 229, "name": "Lincoln Financial Group" },
    { "id": 230, "name": "Line Co" },
    { "id": 231, "name": "Live Well Care" },
    { "id": 232, "name": "Maestro Health (Cigna)" },
    { "id": 233, "name": "Mail Handlers Benefit Plan" },
    { "id": 234, "name": "Manhattan Life" },
    { "id": 235, "name": "MBA Benefit Administrator" },
    { "id": 236, "name": "MCNA - CHIP" },
    { "id": 237, "name": "MCNA - MEDICAID" },
    { "id": 238, "name": "Medical Mutual of Ohio" },
    { "id": 239, "name": "Medico - PPO" },
    { "id": 240, "name": "Medova Healthcare Financial Group" },
    { "id": 241, "name": "Memorial Hermann Health System" },
    { "id": 242, "name": "Meritain Health" },
    { "id": 243, "name": "Metlife Dental - PPO" },
    { "id": 244, "name": "Moda Health" },
    { "id": 245, "name": "Molina Healthcare" },
    { "id": 246, "name": "Multiplan PPO" },
    { "id": 247, "name": "Mutual of Omaha" },
    { "id": 248, "name": "National Care Dental" },
    { "id": 249, "name": "National Elevator Industry Benefits" },
    { "id": 250, "name": "National General Accident and Health" },
    { "id": 251, "name": "Nationwide Insurance" },
    { "id": 252, "name": "Nevada Dental Benefits" },
    { "id": 253, "name": "New Dental Choice" },
    { "id": 254, "name": "New Era Life Company" },
    { "id": 255, "name": "Nexcaliber" },
    { "id": 256, "name": "Nippon Life Benefits" },
    { "id": 257, "name": "Northeast Delta Dental" },
    { "id": 258, "name": "Nova" },
    { "id": 259, "name": "Office Ally" },
    { "id": 260, "name": "Oscar" },
    { "id": 261, "name": "Pan American Life Insurance" },
    { "id": 262, "name": "Physicians Mutual" },
    { "id": 263, "name": "PIPELINE INDUSTRY BENEFIT FUND" },
    { "id": 264, "name": "Planstin Number" },
    { "id": 265, "name": "Point Comfort Underwriters" },
    { "id": 266, "name": "Premera BCBS of TX" },
    { "id": 267, "name": "Principal Life Insurance Co." },
    { "id": 268, "name": "Reliance Standard Life" },
    { "id": 269, "name": "Renaissance Dental" },
    { "id": 270, "name": "Safeguard - Metlife" },
    { "id": 271, "name": "Sana Benefits" },
    { "id": 272, "name": "Seafarers" },
    { "id": 273, "name": "Sisco Benefits" },
    { "id": 274, "name": "Snoqualmie Indian Tribe" },
    { "id": 275, "name": "Solstice Benefits" },
    { "id": 276, "name": "Southern Benefits" },
    { "id": 277, "name": "Southland Benefits Solutions" },
    { "id": 278, "name": "Standard Insurance Company" },
    { "id": 279, "name": "Sunlife Financial" },
    { "id": 280, "name": "Sure Bridge" },
    { "id": 281, "name": "TDA" },
    { "id": 282, "name": "Team Care" },
    { "id": 283, "name": "Texas Health and Human Service" },
    { "id": 284, "name": "The Loomis Company" },
    { "id": 285, "name": "TMHP - MEDICAID" },
    { "id": 286, "name": "TML MultiState IEBP" },
    { "id": 287, "name": "TruAssure" },
    { "id": 288, "name": "Trustmark" },
    { "id": 289, "name": "Ucare" },
    { "id": 290, "name": "UMR" },
    { "id": 291, "name": "Unified Group Services" },
    { "id": 292, "name": "United Concordia - Tricare Dental Plan" },
    { "id": 293, "name": "United Concordia Companies, Inc" },
    { "id": 294, "name": "United Healthcare - AARP" },
    { "id": 295, "name": "United Healthcare - Adult Medicaid" },
    { "id": 296, "name": "United Healthcare - Child Medicaid" },
    { "id": 297, "name": "United Healthcare - Chip" },
    { "id": 298, "name": "United Healthcare - PPO" },
    { "id": 299, "name": "United Healthcare Dual Complete" },
    { "id": 300, "name": "United of Omaha Life insurance co." },
    { "id": 301, "name": "UNUM" },
    { "id": 302, "name": "WebTPA" },
    { "id": 303, "name": "Wellcare Health Plans" },
    { "id": 304, "name": "Wellmark Blue Dental" },
    { "id": 305, "name": "WellPoint" },
    { "id": 306, "name": "Winnie Stowell Hospital District" },
    { "id": 307, "name": "Zenith Admins.Trust" },
    { "id": 308, "name": "Point Comfort Underwriters - UC" },
    { "id": 309, "name": "CareFree Insurance Services" },
    { "id": 310, "name": "Premier Access" },
    { "id": 311, "name": "Delta Dental District of Columbia" },
    { "id": 312, "name": "Southwest Service Life" },
    { "id": 313, "name": "Humana/CompBenefits" },
    { "id": 314, "name": "HMG Healthcare LLC" },
    { "id": 315, "name": "United Concordia- Active Duty Dental" },
    { "id": 316, "name": "Anthem Blue Cross and Blue Shield Ohio" },
    { "id": 317, "name": "Health Plan Inc (Gilsbar)" },
    { "id": 318, "name": "Dental Wise" },
    { "id": 319, "name": "Cypress dental" },
    { "id": 320, "name": "Delta Dental of California - VA" },
    { "id": 321, "name": "Multiplan/PHCS Network" },
    { "id": 322, "name": "SecureCare Group Insurance" },
    { "id": 323, "name": "Teladoc Health, Inc." },
    { "id": 324, "name": "BCBS of Wyoming" }
  ]






export {
  ivRemarksDropdownOptions,
  sourceDropdownOptions,
  planTypeDropdownOptions,
  officeNames,
  insuranceNames
};
